services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - safe_networks
    restart: always
    image: backend
    container_name: backend
    volumes:
      - ./backend:/app
      # removed for now:
      - backend_venv:/app/.venv
    ports:
      - "8000:8000"
  
  mcpserver2:
    build: ./servers/server2
    networks:
      - safe_networks
    container_name: mcpserver_2
    restart: always
    volumes:
      - ./servers/server2:/app
    ports:
      - "8001:8001"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    networks:
      - safe_networks
    container_name: frontend
    image: frontend
    restart: always
    volumes:
      - ./frontend:/app
      - frontend_venv:/app/.venv
    ports:
      - "8501:8501"
    depends_on:
      - backend
      - mcpserver2

volumes:
  backend_venv:
  frontend_venv:

networks:
  safe_networks:
    driver: bridge